version: '3'
services:
  db:
    build:
      context: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thermometrum
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: .
    volumes:
      - "./Go:/go"
      - ./:/app
    container_name: golang_app
    ports:
      - "8001:8001"
    tty: true
    depends_on:
      - db